### ISSUE TITLE
Milestone 2 final checks

### ISSUE THREAD

**Issue by sy25wang** [UBC-MDS/pystockwatch#30]
- [x] Add input checks to functions
- [x] Add output checks to test functions
- [x] Delete individual pytest or pyfunction if any
- [x] Update README with new plots
- [x] Merge all branches
- [x] Manage issues in Kanban board
- [x] Check grammar and spelling
